// <auto-generated />
using KisiApi.context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace KisiApi.Migrations
{
    [DbContext(typeof(contextkisi))]
    [Migration("20220122195402_KisiMG")]
    partial class KisiMG
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("KisiApi.model.Kisi", b =>
                {
                    b.Property<int>("uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ad")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("firma")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("soyad")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("uuid");

                    b.ToTable("Kisi");
                });

            modelBuilder.Entity("KisiApi.model.KisiBilgileri", b =>
                {
                    b.Property<int>("iletisimid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("bilgiicerigi")
                        .HasColumnType("text");

                    b.Property<string>("email")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("konum")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("telefonno")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("uuid")
                        .HasColumnType("integer");

                    b.HasKey("iletisimid");

                    b.ToTable("KisiBilgileri");
                });
#pragma warning restore 612, 618
        }
    }
}
